services:
  - type: web
    name: goldsight
    runtime: python
    region: singapore
    plan: free
    branch: main
    
    buildCommand: |
      pip install --upgrade pip setuptools wheel
      pip install -r requirements-prod.txt
      reflex init
      reflex export --frontend-only
    
    startCommand: "reflex run --env prod --backend-only"
    
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
