services:
  - type: web
    name: goldsight
    env: python
    region: singapore
    plan: free
    buildCommand: "pip install --upgrade pip && pip install -r requirements-prod.txt && reflex init"
    startCommand: "reflex run --env prod --backend-host 0.0.0.0 --backend-port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 8000
